name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Connect to EC2 and Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@$EC2_PUBLIC_IP << 'EOF'
            # Pull latest changes
            cd /home/ec2-user/fastapi-app
            git pull origin main

            # Update Python dependencies
            source venv/bin/activate
            pip install -r requirements.txt

            # Restart services
            sudo systemctl daemon-reload
            sudo systemctl restart fastapi
            sudo systemctl restart nginx
          EOF
